//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resuman
    {
        public int Id_Resumen { get; set; }
        public string Id_Tienda { get; set; }
        public string Id_Registradora { get; set; }
        public Nullable<int> Tickets { get; set; }
    }
}
