//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id_Tickets { get; set; }
        public string Id_Tienda { get; set; }
        public string Id_Registradora { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<int> Ticket1 { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> FechaHora_Creacion { get; set; }
    }
}
